### ISSUE TITLE
Ez

### ISSUE THREAD

**Issue by wendellmeset** [Gav06/Cherry-Client#7]

**Comment by wendellmeset** [comment]
Not gonna lie this is bad but also good 👍 👎

**Comment by wendellmeset** [comment]
Also for some reason this repo appeared in my suggested repos sections 😈

**Comment by wendellmeset** [comment]
Also just a question, why dont you real compiled version lolz

**Comment by AcaiBerii** [comment]
The client is still a work in progress. If you have a functioning brain, you should be able to compile it.

**Comment by wendellmeset** [comment]
I can compile, im a java dev, im just wondering why you dont just release compiled version

**Comment by AcaiBerii** [comment]
because it's still in progress lol?

**Comment by moomooooo** [comment]
i agree

**Comment by Gav06** [comment]
its not done
i will release jar when first release is ready :)

**Comment by moomooooo** [comment]
i disagree
